### ISSUE TITLE
Replace `zip-local` due to security vulnerabilities

### ISSUE THREAD

**Issue by maral** [rowanwins/shp-to-geojson#2]
After installing `shp-to-geojson`, we get this security warning:

```
jszip  <3.8.0
Severity: high
JSZip contains Path Traversal via loadAsync - https://github.com/advisories/GHSA-36fh-84j7-cv5h
No fix available
```

The issue is almost a year old and the library author has not accepted the fix (albeit not sufficient) since May. I saw some other libraries replacing `zip-local` with `adm-zip`, but any other library without security issues would do I guess.

**Comment by rowanwins** [comment]
Fixed in v1.1.0
