### ISSUE TITLE
DBFs aren't quite optional

### ISSUE THREAD

**Issue by qwertie** [rowanwins/shp-to-geojson#6]
Based on how the code is written it looks like DBFs (and PRJs) are supposed to be optional:

        this._tableBuffer = this._options.arraybuffers.dbfBuffer ? buffer.Buffer.from(this._options.arraybuffers.dbfBuffer) : null;
        this._projString = this._options.arraybuffers.projString ? buffer.Buffer.from(this._options.arraybuffers.projString) : null;

However, `summary` crashes in `_numberOfFeatures` when it does `this._tableBuffer.readInt32LE(4)`.

**Comment by rowanwins** [comment]
Fixed in v1.1.0
